spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XE
    username: dev_user
    password: dev_password

  batch:
    jdbc:
      initialize-schema: "never"
    cluster:
      enabled: true
      node-id: ${HOSTNAME:worker}-${random.uuid}
      grid-size: 4
      heartbeat-interval: 5000
  main:
    allow-circular-references: true

debug: true
