spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dev_db?options=-c%20search_path=spring_batch,public
    username: dev_user
    password: dev_password
    hikari:
      maximum-pool-size: 20

  batch:
    msg-channel:
      enabled: false
      master-node: true
      worker-node: false
    single-node:
      enabled: false
    jdbc:
      initialize-schema: "never"
    cluster:
      enabled: true
      node-id: ${HOSTNAME:worker}-${random.uuid}
      grid-size: 4
      heartbeat-interval: 5000
      task-polling-interval: 2000

  main:
    allow-circular-references: true

activemq:
  broker:
    url:
debug: true
