-- maintains cluster nodes heartbeat
CREATE TABLE BATCH_NODES (
    NODE_ID VARCHAR2(200) NOT NULL PRIMARY KEY,
    CREATED_TIME TIMESTAMP NOT NULL,
    LAST_UPDATED_TIME TIMESTAMP NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    HOST_IDENTIFIER VARCHAR2(200),
    CURRENT_LOAD NUMBER(19) DEFAULT 0 NOT NULL
) SEGMENT CREATION IMMEDIATE;

-- Job coordination
CREATE TABLE BATCH_JOB_COORDINATION (
    JOB_EXECUTION_ID NUMBER(19) PRIMARY KEY,
    MASTER_NODE_ID VARCHAR2(200) NOT NULL,
    MASTER_STEP_EXECUTION_ID NUMBER(19) NOT NULL,
    MASTER_STEP_NAME VARCHAR2(100) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    CREATED_TIME TIMESTAMP NOT NULL,
    LAST_UPDATED TIMESTAMP NOT NULL,
    FOREIGN KEY (JOB_EXECUTION_ID) REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) SEGMENT CREATION IMMEDIATE;

-- Partition tracking
CREATE TABLE BATCH_PARTITIONS (
    step_execution_id NUMBER(19) PRIMARY KEY,
    job_execution_id NUMBER(19) NOT NULL,
    partition_key VARCHAR2(100) NOT NULL,
    assigned_node VARCHAR2(100),
    status VARCHAR2(20) NOT NULL CHECK (status IN ('PENDING', 'CLAIMED', 'COMPLETED', 'FAILED')),
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    master_step_execution_id NUMBER(19) NOT NULL,
    is_transferable NUMBER(1) DEFAULT 0,
    CONSTRAINT BAT_PART_FK
        FOREIGN KEY (step_execution_id)
        REFERENCES BATCH_STEP_EXECUTION(step_execution_id)
        ON DELETE CASCADE
) SEGMENT CREATION IMMEDIATE;