#!/usr/bin/env python3
"""Generate the cluster configuration reference table from Spring Boot's
configuration metadata, so docs/configuration.md can never drift from the code.

Reads META-INF/spring-configuration-metadata.json (emitted by
spring-boot-configuration-processor when the core module is compiled) and writes a
Markdown table to docs/_snippets/config-properties.md, which configuration.md
includes via a pymdownx snippet.

Usage (from repo root, after `mvn -pl spring-batch-db-cluster-core compile`):
    python3 scripts/gen-config-table.py
The docs CI regenerates this and fails if the committed copy is stale.
"""
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
META = REPO / "spring-batch-db-cluster-core/target/classes/META-INF/spring-configuration-metadata.json"
OUT = REPO / "docs/_snippets/config-properties.md"

PREFIX = "spring.batch.cluster."
# Deprecated/ignored — documented in prose, kept out of the reference table.
SKIP = {"spring.batch.cluster.node-id"}


def clean(text: str) -> str:
    """Turn Javadoc description fragments into plain Markdown."""
    if not text:
        return ""
    text = re.sub(r"\{@code\s+([^}]*)\}", r"`\1`", text)
    text = re.sub(r"\{@link\s+([^}]*)\}", lambda m: "`" + m.group(1).split()[-1].split(".")[-1] + "`", text)
    text = text.replace("&ndash;", "–").replace("&amp;", "&").replace("&lt;", "<").replace("&gt;", ">")
    # Strip only real HTML tags (Javadoc uses <p>, <code>, ...); leave literals like <prefix>-<uuid>.
    text = re.sub(r"</?(?:p|code|b|i|em|strong|ul|ol|li|br|pre|blockquote|a)\b[^>]*>", "", text, flags=re.I)
    text = re.sub(r"\s+", " ", text).strip()
    return text


def render_default(value) -> str:
    if value is None:
        return "—"                          # em dash: no static default
    if isinstance(value, bool):
        return f"`{str(value).lower()}`"
    return f"`{value}`"


def main() -> int:
    if not META.exists():
        sys.stderr.write(f"metadata not found: {META}\n"
                         "run `mvn -pl spring-batch-db-cluster-core compile` first.\n")
        return 2
    data = json.loads(META.read_text())
    props = [p for p in data.get("properties", [])
             if p.get("name", "").startswith(PREFIX) and p.get("name") not in SKIP]
    props.sort(key=lambda p: p["name"])

    lines = ["<!-- GENERATED by scripts/gen-config-table.py from spring-configuration-metadata.json — do not edit by hand. -->",
             "",
             "| Property | Default | Description |",
             "|---|---|---|"]
    for p in props:
        name = p["name"][len(PREFIX):]
        lines.append(f"| `{name}` | {render_default(p.get('defaultValue'))} | {clean(p.get('description'))} |")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.relative_to(REPO)} ({len(props)} properties)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
