/*
 * Copyright 2025 Janardhan Chejarla
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.github.jchejarla.springbatch.clustering.autoconfigure;

import io.github.jchejarla.springbatch.clustering.autoconfigure.conditions.ConditionalOnClusterEnabled;
import jakarta.annotation.PostConstruct;
import lombok.Getter;
import lombok.Setter;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.boot.sql.init.DatabaseInitializationMode;
import org.springframework.util.StringUtils;

import java.net.InetAddress;
import java.util.UUID;

/**
 * Configuration for database-coordinated Spring Batch clustering, bound from the
 * {@code spring.batch.cluster.*} namespace.
 *
 * <p>Clustering is opt-in: set {@code spring.batch.cluster.enabled=true} to activate it. All other
 * properties are intervals and thresholds (in milliseconds) that tune heartbeating, node
 * liveness/cleanup, worker polling, and recovery. The defaults suit small-to-medium clusters
 * (roughly 2&ndash;20 nodes); tune them to trade coordination-database load against failure-detection
 * latency.</p>
 *
 * @author Janardhan Chejarla
 */
@Slf4j
@Setter
@Getter
@ConfigurationProperties(prefix = "spring.batch.cluster")
@ConditionalOnClusterEnabled
public class BatchClusterProperties {

    /** Master switch for clustering. When {@code false}, none of the cluster components are activated. */
    private boolean enabled = false;

    /** Whether a node registers itself in {@code BATCH_NODES} by host name or IP address. */
    private HostIdentifier hostIdentifier = HostIdentifier.HOST_NAME;

    /**
     * Whether the framework creates its cluster tables on startup, mirroring Spring Batch's own
     * {@code spring.batch.jdbc.initialize-schema}. {@code EMBEDDED} (default) creates them only on
     * genuinely in-memory embedded databases — it does <b>not</b> fire for file-mode H2 or any server
     * database, which must create the cluster tables via {@code spring.sql.init} or a migration tool.
     * {@code ALWAYS} always creates them; {@code NEVER} never does. For production, prefer a managed
     * migration tool (Flyway/Liquibase) with {@code NEVER}, or apply the bundled DDL manually.
     */
    private DatabaseInitializationMode initializeSchema = DatabaseInitializationMode.EMBEDDED;

    /** When {@code true}, emits verbose timing/diagnostic logs for heartbeats and polling. Keep off in production. */
    private boolean tracingEnabled = false;

    /**
     * When {@code true}, records master-side coordination phase timestamps (received, partitioned,
     * distributed, completion-detected) to the append-only {@code BATCH_JOB_PHASE_EVENTS} table, using the
     * database clock. Off by default. Enables later reporting of coordination overhead; the table grows
     * over time, so pair it with a retention/purge policy.
     */
    private boolean capturePhaseTimings = false;

    /**
     * Optional prefix for this node's auto-generated id. Defaults to the machine host name when unset.
     * The actual node id is always {@code <prefix>-<random-uuid>}, generated once at startup, so it is
     * guaranteed unique per JVM and per restart with no manual configuration.
     */
    private String nodeIdPrefix;

    /**
     * The resolved, cluster-unique id for this node, generated at startup as {@code <node-id-prefix>-<uuid>}.
     * <p>The legacy {@code spring.batch.cluster.node-id} property is deprecated and ignored: ids are always
     * generated by the framework so they are unique per JVM and per restart. Use {@code node-id-prefix} for a
     * readable prefix. The host name is also recorded in {@code BATCH_NODES.HOST_IDENTIFIER} for observability.</p>
     */
    private String nodeId;

    /** Maximum number of partition steps this node executes concurrently. */
    private int concurrencyLimitPerNode = 10;

    /** How often this node updates its heartbeat (and refreshes its view of the cluster). */
    private long heartbeatInterval = 3000;

    /** How often the phase-1 sweep runs that marks stale nodes {@code UNREACHABLE}. */
    private long unreachableNodeThreadInterval = 5000;

    /** How often the phase-2 sweep runs that removes long-unreachable nodes from the registry. */
    private long nodeCleanupThreadInterval = 5000;

    /** Heartbeat age after which a node is marked {@code UNREACHABLE} (phase 1 of failover). */
    private long unreachableNodeThreshold = 10000;

    /** Heartbeat age after which an unreachable node is removed and its transferable partitions reassigned (phase 2). */
    private long nodeCleanupThreshold = 30000;

    /** How often a worker polls {@code BATCH_PARTITIONS} for partitions assigned to it. */
    private long taskPollingInterval =1000;

    /** How often a worker prunes its records of completed partition tasks. */
    private long completedTasksCleanupPollingInterval =5000;

    /** How often the master scans for orphaned partitions (assigned to a lost node) to reassign. */
    private long orphanedTasksPollingInterval =1000;

    /** Thread sleep time between each master-side check of overall partition completion. */
    private long masterTaskStatusCheckInterval = 500;

    /**
     * How often each node scans for jobs whose master node has left the cluster, so the stranded
     * (and otherwise permanently {@code STARTED}) job execution can be abandoned and made restartable.
     */
    private long orphanedMasterScanInterval = 10000;

    /**
     * Generates the cluster-unique node id once, after configuration binding, as
     * {@code <node-id-prefix or host name>-<uuid>}.
     */
    @PostConstruct
    void resolveNodeId() {
        if (StringUtils.hasText(nodeId)) {
            log.warn("'spring.batch.cluster.node-id' is deprecated and ignored; node ids are generated automatically. " +
                    "Use 'spring.batch.cluster.node-id-prefix' to set a readable prefix.");
        }
        String prefix = StringUtils.hasText(nodeIdPrefix) ? nodeIdPrefix.trim() : defaultHostName();
        this.nodeId = prefix + "-" + UUID.randomUUID();
    }

    private String defaultHostName() {
        try {
            return InetAddress.getLocalHost().getHostName();
        } catch (Exception e) {
            return "node";
        }
    }

    public enum HostIdentifier {
        HOST_NAME,
        IP_ADDRESS
    }
}
